# Generated by Django 4.2.8 on 2024-03-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number of the room')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacity of the room')),
                ('price_per_night', models.PositiveIntegerField(verbose_name='Price')),
                ('is_used', models.BooleanField()),
                ('descriprion', models.TextField(verbose_name='About room')),
                ('hotels', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hotel.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
