# Generated by Django 4.2.8 on 2024-03-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
    ]
